export const SEED = [
  {
    id: 1,
    date: "2025-03-01T10:00:00Z",
    project_name: "Okara AI CMO",
    one_liner: "An AI that acts as your Chief Marketing Officer and deploys agents to get you traffic.",
    what_it_does: "You enter your website URL and Okara deploys a team of AI agents to analyze your product and drive traffic and user acquisition. It positions itself as a fully autonomous CMO replacement.",
    who_built_it: "askOkara",
    category: "agent",
    tech_stack: ["AI agents", "web analysis"],
    novelty_score: 6,
    novelty_verdict: "Solid Execution",
    novelty_reasoning: "The CMO-as-agent angle is well framed but marketing automation agents are a crowded space. The deployment-from-URL simplicity is the real differentiator.",
    hook: "Enter your website and it deploys a team of agents to help you get traffic and users.",
    missing: "What does get traffic actually mean here? SEO? Ads? Outreach? No specifics on mechanisms.",
    editorial_note: "Smart positioning, thin on substance. The real test is whether any of those agents actually move the needle.",
  },
  {
    id: 2,
    date: "2025-03-01T10:01:00Z",
    project_name: "Moonshot Leverage",
    one_liner: "Crypto leverage trading up to 250x, accessible via Apple Pay.",
    what_it_does: "Moonshot Leverage lets users go long or short on BTC, ETH, and SOL with up to 250x leverage using Apple Pay and other payment methods. It is currently live in select regions.",
    who_built_it: "moonshot",
    category: "app",
    tech_stack: ["crypto", "Apple Pay"],
    novelty_score: 4,
    novelty_verdict: "Repackaged",
    novelty_reasoning: "Leverage trading is ancient in crypto. The Apple Pay on-ramp is more accessible, but the core product is not new.",
    hook: "Long or short BTC, ETH, SOL with up to 250x your cash.",
    missing: "Who is this actually for? Retail traders plus 250x leverage is a liquidation machine.",
    editorial_note: "Making financial self-destruction frictionless is not the same as innovation.",
  },
  {
    id: 3,
    date: "2025-03-01T10:02:00Z",
    project_name: "Tempo Machine Payments Protocol",
    one_liner: "An open standard for machines to pay each other, launching alongside the Tempo mainnet.",
    what_it_does: "Tempo launched its mainnet with public RPC endpoints for builders. Alongside it they introduced the Machine Payments Protocol, an open standard designed for autonomous machine-to-machine payments.",
    who_built_it: "tempo",
    category: "infra",
    tech_stack: ["blockchain", "RPC", "payments protocol"],
    novelty_score: 8,
    novelty_verdict: "Genuinely New",
    novelty_reasoning: "Machine-to-machine payments as an open standard is ahead of the current market. Most agent payment infrastructure is proprietary.",
    hook: "An open standard for machine payments, built for agents paying agents.",
    missing: "Who is adopting this? An open standard with no listed integrations is just a spec.",
    editorial_note: "The right bet at the right time. Whether it becomes infrastructure or vaporware depends on developer adoption.",
  },
  {
    id: 4,
    date: "2025-03-01T10:03:00Z",
    project_name: "Attention Residuals (Kimi)",
    one_liner: "A neural network component that lets models selectively remember earlier layers instead of accumulating everything uniformly.",
    what_it_does: "Kimi introduces Attention Residuals as a replacement for standard depth-wise residual connections in neural networks. Instead of fixed uniform accumulation, the model learns input-dependent attention over preceding layers.",
    who_built_it: "Kimi / Moonshot AI",
    category: "framework",
    tech_stack: ["transformer architecture", "residual networks", "48B MoE"],
    novelty_score: 9,
    novelty_verdict: "Genuinely New",
    novelty_reasoning: "This is a fundamental architectural contribution, not a product announcement. It addresses a real dilution problem in deep networks.",
    hook: "Replacing fixed residual connections with learned attention over preceding layers.",
    missing: "Open weights? Open source implementation? The report exists but code availability is unclear.",
    editorial_note: "One of the few entries that reads like actual research instead of product packaging.",
  },
  {
    id: 5,
    date: "2025-03-01T10:04:00Z",
    project_name: "Cloudflare /crawl",
    one_liner: "One API call to crawl an entire website and get back clean HTML, Markdown, or JSON.",
    what_it_does: "Cloudflare added a /crawl endpoint that crawls an entire site with a single API call, no browser management or scripting required. It returns content in HTML, Markdown, or JSON format.",
    who_built_it: "CloudflareDev",
    category: "tool",
    tech_stack: ["Cloudflare", "web crawling", "API"],
    novelty_score: 7,
    novelty_verdict: "Solid Execution",
    novelty_reasoning: "Firecrawl and Jina already do this, but Cloudflare distributing it natively changes the economics and reliability.",
    hook: "One API call. Entire site crawled. No scripts, no browser management.",
    missing: "Pricing model? Rate limits? The economics change everything here.",
    editorial_note: "Cloudflare keeps eating the middleware layer. Smart, and bad news for scraping startups.",
  },
  {
    id: 6,
    date: "2025-03-01T10:05:00Z",
    project_name: "CashClaw",
    one_liner: "An open-source autonomous agent that finds work, does it, gets paid, and learns to earn more over time.",
    what_it_does: "CashClaw is an agent framework built on Moltlaunch infrastructure that autonomously finds paid work, delivers it, collects payment, reads feedback, and improves. Discovery, reputation, identity, and payments are handled by the platform.",
    who_built_it: "moltlaunch",
    category: "agent",
    tech_stack: ["Moltlaunch", "OpenClaw", "open source"],
    novelty_score: 8,
    novelty_verdict: "Genuinely New",
    novelty_reasoning: "A fully autonomous earn-and-learn loop for agents as an open-source framework is a concrete step toward economically independent agents.",
    hook: "The agent finds work, gets paid, reads feedback, finds better tools, finds more work.",
    missing: "What kinds of work does it actually find? Who is paying agents on Moltlaunch?",
    editorial_note: "If it ships as described, this is one of the more radical entries in the list.",
  },
  {
    id: 7,
    date: "2025-03-01T10:06:00Z",
    project_name: "FlashCompact",
    one_liner: "A specialized model that compresses 200k token contexts down to 50k in about 1.5 seconds.",
    what_it_does: "FlashCompact is the first model purpose-built for context compaction. It processes 33,000 tokens per second and compresses a 200k token context to 50k in roughly 1.5 seconds.",
    who_built_it: "morphllm",
    category: "framework",
    tech_stack: ["context compaction", "LLM", "inference"],
    novelty_score: 9,
    novelty_verdict: "Genuinely New",
    novelty_reasoning: "A specialized model trained for context compression rather than general summarization is architecturally novel and operationally useful.",
    hook: "33,000 tokens per second. 200k context to 50k in 1.5 seconds.",
    missing: "What is the quality loss at that compression ratio for downstream reasoning?",
    editorial_note: "Infrastructure-specialized models are underexplored, and this is one of the stronger examples.",
  },
  {
    id: 8,
    date: "2025-03-01T10:07:00Z",
    project_name: "Unsloth Studio",
    one_liner: "An open-source web UI for training and running over 500 LLMs locally at 2x speed with 70% less VRAM.",
    what_it_does: "Unsloth Studio is an open-source interface for training and running language models locally on Mac, Windows, or Linux. It supports GGUF, vision, audio, and embedding models, and can auto-generate datasets from PDFs and CSVs.",
    who_built_it: "UnslothAI",
    category: "tool",
    tech_stack: ["open source", "LLM training", "GGUF", "local inference"],
    novelty_score: 8,
    novelty_verdict: "Genuinely New",
    novelty_reasoning: "The efficiency gains are documented, and packaging them in a broad local UI opens the stack to new users.",
    hook: "Train 500+ models at 2x speed with 70% less VRAM.",
    missing: "How reliable is the dataset auto-generation path from PDFs?",
    editorial_note: "One of the more practically useful open-source releases in the list.",
  },
  {
    id: 9,
    date: "2025-03-01T10:08:00Z",
    project_name: "Simile",
    one_liner: "A $100M-funded startup building the most accurate simulations of human behavior.",
    what_it_does: "Simile raised $100M from Index, Hanabi, and others including Karpathy, Fei-Fei Li, and Adam D'Angelo to tackle large-scale simulation of human behavior.",
    who_built_it: "joon_s_pk",
    category: "infra",
    tech_stack: ["human simulation", "AI"],
    novelty_score: 9,
    novelty_verdict: "Genuinely New",
    novelty_reasoning: "Accurate human behavior simulation at scale would have major impact across product development, policy, and research.",
    hook: "Simulating human behavior is one of the most consequential and technically difficult problems of our time.",
    missing: "What is the actual product? API, simulator, or research platform is still unclear.",
    editorial_note: "The backers alone make this worth watching, but the product definition is still opaque.",
  },
  {
    id: 10,
    date: "2025-03-01T10:09:00Z",
    project_name: "Claude Code Review",
    one_liner: "When a pull request opens, Claude automatically dispatches agents to review it for bugs.",
    what_it_does: "Anthropic added a Code Review feature to Claude Code that triggers when a PR is opened. A team of agents scans the diff and hunts for bugs as part of the review workflow.",
    who_built_it: "Anthropic",
    category: "agent",
    tech_stack: ["Claude", "GitHub", "agents"],
    novelty_score: 7,
    novelty_verdict: "Solid Execution",
    novelty_reasoning: "Automated PR review exists already, but a tighter native integration in Claude Code is a meaningful workflow improvement.",
    hook: "When a PR opens, Claude dispatches a team of agents to hunt for bugs.",
    missing: "What is the pricing model and required setup on both sides of the review flow?",
    editorial_note: "This is Claude Code moving closer to becoming a full development environment.",
  },
  {
    id: 11,
    date: "2025-03-01T10:10:00Z",
    project_name: "Manus Desktop",
    one_liner: "Manus moved from the cloud to your local machine with direct access to your computer.",
    what_it_does: "Manus introduced My Computer, a desktop app feature that lets the Manus agent run locally on your machine rather than in the cloud. The agent gets direct access to local files and applications.",
    who_built_it: "ManusAI",
    category: "agent",
    tech_stack: ["desktop", "local AI", "agent"],
    novelty_score: 7,
    novelty_verdict: "Solid Execution",
    novelty_reasoning: "Local execution of a general-purpose agent is a meaningful privacy and latency improvement over cloud-only systems.",
    hook: "Taking Manus out of the cloud and putting it on your desktop.",
    missing: "What can it actually access locally? The scope of access defines the product.",
    editorial_note: "The privacy angle should probably be the primary positioning, not a side note.",
  },
  {
    id: 12,
    date: "2025-03-01T10:11:00Z",
    project_name: "Replit Agent 4",
    one_liner: "An AI built for creative collaboration between humans and agents with infinite canvas and parallel agent execution.",
    what_it_does: "Replit launched Agent 4 with an infinite canvas for design, team collaboration, parallel agent execution, and shipping of full apps, sites, and slides.",
    who_built_it: "amasad / Replit",
    category: "agent",
    tech_stack: ["Replit", "agents", "canvas"],
    novelty_score: 7,
    novelty_verdict: "Solid Execution",
    novelty_reasoning: "The infinite canvas framing and parallel agents change the workflow even if the category itself is already crowded.",
    hook: "Software is not merely technical anymore. It is creative.",
    missing: "What does parallel agents mean in practice? How are conflicting threads managed?",
    editorial_note: "A strong repositioning move, but the operational details matter more than the framing.",
  },
];
